In [15]:
#install required libraries
import pandas as pd
import numpy as np
#data visualization packages
import matplotlib.pyplot as plt
#keras packages
import keras
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.layers import Dropout
#model evaluation packages
from sklearn.metrics import f1_score, roc_auc_score, log_loss
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.metrics import accuracy_score

In [6]:
import tensorflow.keras as tk
mnist = tk.datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [7]:
#reshape data from 3-D to 2-D array
X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
#feature scaling
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()
#fit and transform training dataset
X_train = minmax.fit_transform(X_train)
#transform testing dataset
X_test = minmax.transform(X_test)
print('Number of unique classes: ', len(np.unique(y_train)))
print('Classes: ', np.unique(y_train))

Number of unique classes:  10
Classes:  [0 1 2 3 4 5 6 7 8 9]


In [8]:

classifier_e25 = Sequential()

classifier_e25.add(Dense(input_dim = X_train.shape[1], units = 256, kernel_initializer='uniform', activation='relu'))

classifier_e25.add(Dense(units = 10, kernel_initializer='uniform', activation='softmax'))

classifier_e25.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

classifier_e25.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 256)               200960    
                                                                 
 dense_1 (Dense)             (None, 10)                2570      
                                                                 
Total params: 203,530
Trainable params: 203,530
Non-trainable params: 0
_________________________________________________________________


In [9]:
#fit training dataset into the model
classifier_e25_fit = classifier_e25.fit(X_train, y_train, epochs=25, verbose=0)

In [11]:
#evaluate the model for testing dataset
test_loss_e25 = classifier_e25.evaluate(X_test, y_test, verbose=0)

In [12]:
test_loss_e25

[0.1258549690246582, 0.979200005531311]

In [14]:
 y_pred = classifier_e25.predict(X_test)

In [17]:
y_pred

array([[5.8801318e-16, 2.7756191e-23, 3.0341705e-18, ..., 1.0000000e+00,
        5.1247448e-19, 2.3408050e-10],
       [3.1200584e-15, 1.0893270e-22, 1.0000000e+00, ..., 1.0895124e-25,
        8.2530992e-21, 7.2293443e-32],
       [1.1808522e-15, 9.9999952e-01, 2.8472538e-09, ..., 2.8867031e-08,
        5.2547773e-07, 7.7853900e-16],
       ...,
       [8.9985563e-36, 1.6803729e-31, 1.0370298e-32, ..., 3.1922194e-16,
        1.2551633e-20, 8.3573177e-13],
       [1.1643982e-19, 2.8218605e-28, 7.9820920e-25, ..., 1.9184640e-20,
        4.9231137e-14, 1.1826521e-29],
       [1.2659547e-26, 9.3981664e-34, 8.9568598e-25, ..., 3.3696130e-30,
        1.5294865e-27, 3.8857334e-29]], dtype=float32)

In [18]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [22]:
predict_x = classifier_e25.predict(X_test)


In [23]:
predict_x

array([[5.8801318e-16, 2.7756191e-23, 3.0341705e-18, ..., 1.0000000e+00,
        5.1247448e-19, 2.3408050e-10],
       [3.1200584e-15, 1.0893270e-22, 1.0000000e+00, ..., 1.0895124e-25,
        8.2530992e-21, 7.2293443e-32],
       [1.1808522e-15, 9.9999952e-01, 2.8472538e-09, ..., 2.8867031e-08,
        5.2547773e-07, 7.7853900e-16],
       ...,
       [8.9985563e-36, 1.6803729e-31, 1.0370298e-32, ..., 3.1922194e-16,
        1.2551633e-20, 8.3573177e-13],
       [1.1643982e-19, 2.8218605e-28, 7.9820920e-25, ..., 1.9184640e-20,
        4.9231137e-14, 1.1826521e-29],
       [1.2659547e-26, 9.3981664e-34, 8.9568598e-25, ..., 3.3696130e-30,
        1.5294865e-27, 3.8857334e-29]], dtype=float32)

In [ ]:
classes_x = np.argmax(predict_x,axis=1)

In [26]:
classes_x 

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [29]:
accuracy_score(y_test, classes_x)

0.9792